### ISSUE TITLE
Add ability to generate id's

### ISSUE THREAD

**Issue by jonathonadams** [stefanprobst/remark-extract-toc#1]
The current recommended approach to generate `id`'s as per the docs is to use [remark-slug](https://www.npmjs.com/package/remark-slug).
>Note that this plugin does not generate any ids, you will probably want to combine it with `remark-slug`

Although `remark-slug` is not currently deprecated, it is however flagged as legacy and advised not to use. The recommended approach to is to use [rehype-slug](https://github.com/rehypejs/rehype-slug) to generate the `id`'s once converted to `html`, however this is downstream of this plugin.

It would be nice if the ability to generate `id`'s is added to the this packages as an optional argument so that this package can still be used while following the recommended approach of generating `id`/`slug`'s , i.e. something along the lines of:

```ts
// id can either be a boolean (defaulting to `github-slugger`) or
// a function to generate `id` from the heading value 
interface ExtractToCOptions {
  id: boolean | (value: string) => string
}

unified()
    .use(remarkParse)
    .use(extractToc, { id: true }) // default: false
```

Happy to put a PR together if you like.

**Comment by stefanprobst** [comment]
hi, you could use [`rehype-extract-toc`](https://github.com/stefanprobst/rehype-extract-toc) together with [`rehype-slug`](https://github.com/rehypejs/rehype-slug) - would that work for your usecase?

**Comment by jonathonadams** [comment]
Thanks @stefanprobst . I'm not sure why I couldn't find that in my searching but yes it does solve my use case.

Jono
